name: Install Tools
description: Install Python, Conan, and CMake for both Windows and Linux
runs:
  using: "composite"
  steps:
    # Step 1: Setup Python (works for both OS)
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # Step 2: Install Conan on Linux
    - name: Install Conan on Linux
      if: runner.os == 'Linux'
      run: |
        python -m pip install --upgrade pip
        pip install conan
        conan --version
      shell: bash

    # Step 3: Install Pip on Windows
    - name: Install pip on Windows
      if: runner.os == 'Windows'
      run: |
        python -m pip install --upgrade pip
      shell: cmd

    # Step 4: Install CMake on Linux
    - name: Install CMake on Linux
      if: runner.os == 'Linux'
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.28.0'

    # Step 5: Install CMake on Windows
    - name: Install CMake on Windows
      if: runner.os == 'Windows'
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.28.0'
