name: Compress Build Artifacts
description: Compress the bin folder into versioned archive per OS
runs:
  using: "composite"
  steps:
    - name: Copy and organize artifacts (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        # Create output directory
        New-Item -ItemType Directory -Path "Landcraft-${{ github.ref_name }}" -Force | Out-Null
        
        # Copy bin contents to root
        Copy-Item -Path "bin\*" -Destination "Landcraft-${{ github.ref_name }}" -Recurse -Force
        
        # Copy assets folder
        Copy-Item -Path "assets" -Destination "Landcraft-${{ github.ref_name }}\assets" -Recurse -Force
        
        # Compress the result
        Compress-Archive -Path "Landcraft-${{ github.ref_name }}" -DestinationPath "Landcraft-${{ github.ref_name }}-Windows.zip"

    - name: Copy and organize artifacts (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        # Create output directory
        mkdir -p "Landcraft-${{ github.ref_name }}"
        
        # Copy bin contents to root
        cp -r bin/* "Landcraft-${{ github.ref_name }}/"
        
        # Copy assets folder
        cp -r assets "Landcraft-${{ github.ref_name }}/"
        
        # Compress the result
        tar -czf "Landcraft-${{ github.ref_name }}-Linux.tar.gz" "Landcraft-${{ github.ref_name }}"
