name: Run Quick Executable Test
description: Run a simple test to ensure the built executable launches
runs:
  using: "composite"
  steps:
    - name: Run test on Windows
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        if exist .\bin\landcraft.exe (
          echo Binary found
        ) else (
          echo Binary not found & exit 1
        )
    - name: Run test on Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        if [ -x ./bin/landcraft ]; then
          echo "Binary found"
        else
          echo "Binary not found" >&2
          exit 1
        fi